/* eslint-disable */
// ⚠️  AUTO-GENERATED by scripts/generate-foundation-tokens.js
//     Source of truth: Light.tokens.json / Dark.tokens.json
//     DO NOT EDIT DIRECTLY. Re-run the script to regenerate.

export type SemanticToken = {
  /** Full CSS variable name incl. leading -- */
  name: string;
  /** Leaf key as stored in Figma (e.g. `on-blue-secondary`) */
  leafName: string;
  /** Value on light theme */
  light: string;
  /** Value on dark theme */
  dark: string;
  /** Figma alias for light theme (e.g. `Blue/500`) */
  lightAlias: string | null;
  /** Figma alias for dark theme */
  darkAlias: string | null;
};

export type SemanticSection = {
  /** Slug for anchor / key */
  id: string;
  /** Original Figma path (e.g. `Context/Foreground/Blue`) */
  path: string;
  tokens: SemanticToken[];
};

export type SemanticGroupId = "foreground" | "background" | "tint" | "accent" | "border" | "borderNeutral" | "borderSurface" | "borderOpacity" | "opacity" | "bgTransparency";

export type SemanticGroup = {
  id: SemanticGroupId;
  title: string;
  description: string;
  sections: SemanticSection[];
};

export const SEMANTIC_GROUPS: SemanticGroup[] = [
  {
    id: "foreground",
    title: "Foreground",
    description: "텍스트·아이콘 전경 색상.",
    sections: [
      {
        id: "context-foreground-surface",
        path: "Context/Foreground/Surface",
        tokens: [
          {"name":"--context-foreground-surface-on-surface-base","leafName":"on-surface-base","light":"#141518","dark":"#F4F4F5","lightAlias":"Gray/900","darkAlias":"Gray/25"},
          {"name":"--context-foreground-surface-on-suface-white","leafName":"on-suface-white","light":"#FFFFFF","dark":"#1F2025","lightAlias":"Gray/White","darkAlias":"Gray/850"},
          {"name":"--context-foreground-surface-on-suface-black","leafName":"on-suface-black","light":"#000000","dark":"#FFFFFF","lightAlias":"Gray/Black","darkAlias":"Gray/White"},
          {"name":"--context-foreground-surface-on-suface-invert","leafName":"on-suface-invert","light":"#F4F4F5","dark":"#141518","lightAlias":"Gray/25","darkAlias":"Gray/900"},
          {"name":"--context-foreground-surface-on-surface-secondary","leafName":"on-surface-secondary","light":"#B3B4BC","dark":"#565967","lightAlias":"Gray/200","darkAlias":"Gray/500"},
          {"name":"--context-foreground-surface-on-surface-teriary","leafName":"on-surface-teriary","light":"#9698A3","dark":"#787A88","lightAlias":"Gray/300","darkAlias":"Gray/400"},
          {"name":"--context-foreground-surface-on-surface-hint","leafName":"on-surface-hint","light":"#787A88","dark":"#787A88","lightAlias":"Gray/400","darkAlias":"Gray/400"},
          {"name":"--context-foreground-surface-on-surface-hint-muted","leafName":"on-surface-hint-muted","light":"#9698A3","dark":"#787A88","lightAlias":"Gray/300","darkAlias":"Gray/400"},
          {"name":"--context-foreground-surface-on-surface","leafName":"on-surface","light":"#565967","dark":"#9698A3","lightAlias":"Gray/500","darkAlias":"Gray/300"},
          {"name":"--context-foreground-surface-on-surface-hover","leafName":"on-surface-hover","light":"#434551","dark":"#787A88","lightAlias":"Gray/600","darkAlias":"Gray/400"},
          {"name":"--context-foreground-surface-on-surface-selected","leafName":"on-surface-selected","light":"#434551","dark":"#B3B4BC","lightAlias":"Gray/600","darkAlias":"Gray/200"},
          {"name":"--context-foreground-surface-on-surface-disabled","leafName":"on-surface-disabled","light":"#B3B4BC","dark":"#787A88","lightAlias":"Gray/200","darkAlias":"Gray/400"},
        ],
      },
      {
        id: "context-foreground-neutral",
        path: "Context/Foreground/Neutral",
        tokens: [
          {"name":"--context-foreground-neutral-on-neutral-base","leafName":"on-neutral-base","light":"#141518","dark":"#141518","lightAlias":"Gray/900","darkAlias":"Gray/900"},
          {"name":"--context-foreground-neutral-on-neutral-white","leafName":"on-neutral-white","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Gray/White","darkAlias":"Gray/White"},
          {"name":"--context-foreground-neutral-on-neutral-invert","leafName":"on-neutral-invert","light":"#F4F4F5","dark":"#F4F4F5","lightAlias":"Gray/25","darkAlias":"Gray/25"},
          {"name":"--context-foreground-neutral-on-neutral-secondary","leafName":"on-neutral-secondary","light":"#26282E","dark":"#26282E","lightAlias":"Gray/800","darkAlias":"Gray/800"},
          {"name":"--context-foreground-neutral-on-neutral-teriary","leafName":"on-neutral-teriary","light":"#434551","dark":"#434551","lightAlias":"Gray/600","darkAlias":"Gray/600"},
          {"name":"--context-foreground-neutral-on-neutral-hint","leafName":"on-neutral-hint","light":"#787A88","dark":"#787A88","lightAlias":"Gray/400","darkAlias":"Gray/400"},
          {"name":"--context-foreground-neutral-on-neutral-hint-muted","leafName":"on-neutral-hint-muted","light":"#9698A3","dark":"#9698A3","lightAlias":"Gray/300","darkAlias":"Gray/300"},
          {"name":"--context-foreground-neutral-on-neutral","leafName":"on-neutral","light":"#565967","dark":"#565967","lightAlias":"Gray/500","darkAlias":"Gray/500"},
          {"name":"--context-foreground-neutral-on-neutral-hover","leafName":"on-neutral-hover","light":"#434551","dark":"#787A88","lightAlias":"Gray/600","darkAlias":"Gray/400"},
          {"name":"--context-foreground-neutral-on-neutral-readonly","leafName":"on-neutral-readonly","light":"#141518","dark":"#141518","lightAlias":"Gray/900","darkAlias":"Gray/900"},
          {"name":"--context-foreground-neutral-on-neutral-disabled","leafName":"on-neutral-disabled","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
        ],
      },
      {
        id: "context-foreground-icon-surface",
        path: "Context/Foreground/Icon-Surface",
        tokens: [
          {"name":"--context-foreground-icon-surface-icon-surface-base","leafName":"Icon-surface-base","light":"#141518","dark":"#F4F4F5","lightAlias":"Gray/900","darkAlias":"Gray/25"},
          {"name":"--context-foreground-icon-surface-icon-suface-invert","leafName":"Icon-suface-invert","light":"#F4F4F5","dark":"#141518","lightAlias":"Gray/25","darkAlias":"Gray/900"},
          {"name":"--context-foreground-icon-surface-icon-surface-secondary","leafName":"Icon-surface-secondary","light":"#B3B4BC","dark":"#434551","lightAlias":"Gray/200","darkAlias":"Gray/600"},
          {"name":"--context-foreground-icon-surface-icon-surface-teriary","leafName":"Icon-surface-teriary","light":"#787A88","dark":"#9698A3","lightAlias":"Gray/400","darkAlias":"Gray/300"},
          {"name":"--context-foreground-icon-surface-icon-surface","leafName":"Icon-surface","light":"#565967","dark":"#9698A3","lightAlias":"Gray/500","darkAlias":"Gray/300"},
          {"name":"--context-foreground-icon-surface-icon-surface-hover","leafName":"Icon-surface-hover","light":"#434551","dark":"#B3B4BC","lightAlias":"Gray/600","darkAlias":"Gray/200"},
          {"name":"--context-foreground-icon-surface-icon-surface-selected","leafName":"Icon-surface-selected","light":"#434551","dark":"#D7D8DC","lightAlias":"Gray/600","darkAlias":"Gray/100"},
          {"name":"--context-foreground-icon-surface-icon-surface-readonly","leafName":"Icon-surface-readonly","light":"#B3B4BC","dark":"#787A88","lightAlias":"Gray/200","darkAlias":"Gray/400"},
          {"name":"--context-foreground-icon-surface-icon-surface-disabled","leafName":"Icon-surface-disabled","light":"#B3B4BC","dark":"#787A88","lightAlias":"Gray/200","darkAlias":"Gray/400"},
        ],
      },
      {
        id: "context-foreground-icon-neutral",
        path: "Context/Foreground/Icon-Neutral",
        tokens: [
          {"name":"--context-foreground-icon-neutral-icon-neutral-white","leafName":"icon-neutral-white","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Gray/White","darkAlias":"Gray/White"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-invert","leafName":"icon-neutral-invert","light":"#F4F4F5","dark":"#F4F4F5","lightAlias":"Gray/25","darkAlias":"Gray/25"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-teriary","leafName":"icon-neutral-teriary","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-secondary","leafName":"icon-neutral-secondary","light":"#787A88","dark":"#787A88","lightAlias":"Gray/400","darkAlias":"Gray/400"},
          {"name":"--context-foreground-icon-neutral-icon-neutral","leafName":"icon-neutral","light":"#565967","dark":"#565967","lightAlias":"Gray/500","darkAlias":"Gray/500"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-hover","leafName":"icon-neutral-hover","light":"#434551","dark":"#434551","lightAlias":"Gray/600","darkAlias":"Gray/600"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-selected","leafName":"icon-neutral-selected","light":"#434551","dark":"#434551","lightAlias":"Gray/600","darkAlias":"Gray/600"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-readonly","leafName":"icon-neutral-readonly","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
          {"name":"--context-foreground-icon-neutral-icon-neutral-disabled","leafName":"icon-neutral-disabled","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
        ],
      },
      {
        id: "context-foreground-primary",
        path: "Context/Foreground/Primary",
        tokens: [
          {"name":"--context-foreground-primary-on-primary","leafName":"on-primary","light":"#3F9BAE","dark":"#9EF7EE","lightAlias":"Mint/700","darkAlias":"Mint/400"},
          {"name":"--context-foreground-primary-on-primary-secondary","leafName":"on-primary-secondary","light":"#7EF2F1","dark":"#7EF2F1","lightAlias":"Mint/500","darkAlias":"Mint/500"},
          {"name":"--context-foreground-primary-on-primary-hover","leafName":"on-primary-hover","light":"#28738C","dark":"#CDFDF0","lightAlias":"Mint/800","darkAlias":"Mint/200"},
          {"name":"--context-foreground-primary-on-primary-selected","leafName":"on-primary-selected","light":"#5CC7D0","dark":"#5CC7D0","lightAlias":"Mint/600","darkAlias":"Mint/600"},
          {"name":"--context-foreground-primary-on-primary-disabled","leafName":"on-primary-disabled","light":"#8BC5C3","dark":"#8BC5C3","lightAlias":null,"darkAlias":null},
        ],
      },
      {
        id: "context-foreground-error",
        path: "Context/Foreground/Error",
        tokens: [
          {"name":"--context-foreground-error-on-error","leafName":"on-error","light":"#FF312E","dark":"#FF5A58","lightAlias":"Red/500","darkAlias":"Red/400"},
          {"name":"--context-foreground-error-on-error-secondary","leafName":"on-error-secondary","light":"#FF5A58","dark":"#FF312E","lightAlias":"Red/400","darkAlias":"Red/500"},
          {"name":"--context-foreground-error-on-error-hover","leafName":"on-error-hover","light":"#CC2725","dark":"#FF8382","lightAlias":"Red/600","darkAlias":"Red/300"},
          {"name":"--context-foreground-error-on-error-selected","leafName":"on-error-selected","light":"#991D1C","dark":"#CC2725","lightAlias":"Red/700","darkAlias":"Red/600"},
          {"name":"--context-foreground-error-on-error-disabled","leafName":"on-error-disabled","light":"#FFD6D5","dark":"#661412","lightAlias":"Red/100","darkAlias":"Red/800"},
        ],
      },
      {
        id: "context-foreground-warning",
        path: "Context/Foreground/Warning",
        tokens: [
          {"name":"--context-foreground-warning-on-warning","leafName":"on-warning","light":"#FF8F0E","dark":"#FF8F0E","lightAlias":"Orange/500","darkAlias":"Orange/500"},
          {"name":"--context-foreground-warning-on-warning-secondary","leafName":"on-warning-secondary","light":"#FFA53E","dark":"#FF8F0E","lightAlias":"Orange/400","darkAlias":"Orange/500"},
          {"name":"--context-foreground-warning-on-warning-hover","leafName":"on-warning-Hover","light":"#CC720B","dark":"#FFBC6E","lightAlias":"Orange/600","darkAlias":"Orange/300"},
          {"name":"--context-foreground-warning-on-warning-selected","leafName":"on-warning-selected","light":"#995608","dark":"#CC720B","lightAlias":"Orange/700","darkAlias":"Orange/600"},
          {"name":"--context-foreground-warning-on-warning-disabled","leafName":"on-warning-disabled","light":"#FFDDB6","dark":"#663906","lightAlias":"Orange/100","darkAlias":"Orange/800"},
        ],
      },
      {
        id: "context-foreground-success",
        path: "Context/Foreground/Success",
        tokens: [
          {"name":"--context-foreground-success-on-success","leafName":"on-success","light":"#09B200","dark":"#84D980","lightAlias":"Green/500","darkAlias":"Green/300"},
          {"name":"--context-foreground-success-on-success-secondary","leafName":"on-success-secondary","light":"#3AC133","dark":"#09B200","lightAlias":"Green/400","darkAlias":"Green/500"},
          {"name":"--context-foreground-success-on-success-hover","leafName":"on-success-hover","light":"#056B00","dark":"#A9E4A6","lightAlias":"Green/700","darkAlias":"Green/200"},
          {"name":"--context-foreground-success-on-success-selected","leafName":"on-success-selected","light":"#044700","dark":"#3AC133","lightAlias":"Green/800","darkAlias":"Green/400"},
          {"name":"--context-foreground-success-on-success-disabled","leafName":"on-success-disabled","light":"#CEF0CC","dark":"#044700","lightAlias":"Green/100","darkAlias":"Green/800"},
        ],
      },
      {
        id: "context-foreground-progress",
        path: "Context/Foreground/Progress",
        tokens: [
          {"name":"--context-foreground-progress-on-progress","leafName":"on-progress","light":"#0DCAF0","dark":"#3DD5F3","lightAlias":"Cyan/500","darkAlias":"Cyan/400"},
          {"name":"--context-foreground-progress-on-progress-secondary","leafName":"on-progress-secondary","light":"#3DD5F3","dark":"#0DCAF0","lightAlias":"Cyan/400","darkAlias":"Cyan/500"},
          {"name":"--context-foreground-progress-on-progress-hover","leafName":"on-progress-hover","light":"#0AA2C0","dark":"#9EEAF9","lightAlias":"Cyan/600","darkAlias":"Cyan/200"},
          {"name":"--context-foreground-progress-on-progress-selected","leafName":"on-progress-selected","light":"#0D6A7D","dark":"#0AA2C0","lightAlias":"Cyan/700","darkAlias":"Cyan/600"},
          {"name":"--context-foreground-progress-on-progress-disabled","leafName":"on-progress-disabled","light":"#CFF4FC","dark":"#064855","lightAlias":"Cyan/100","darkAlias":"Cyan/800"},
        ],
      },
      {
        id: "context-foreground-blue",
        path: "Context/Foreground/Blue",
        tokens: [
          {"name":"--context-foreground-blue-on-blue","leafName":"on-blue","light":"#316CF4","dark":"#5289F5","lightAlias":"Blue/500","darkAlias":"Blue/400"},
          {"name":"--context-foreground-blue-on-blue-secondary","leafName":"on-blue-secondary","light":"#5289F5","dark":"#316CF4","lightAlias":"Blue/400","darkAlias":"Blue/500"},
          {"name":"--context-foreground-blue-on-blue-hover","leafName":"on-blue-hover","light":"#2757C3","dark":"#7BA6F7","lightAlias":"Blue/600","darkAlias":"Blue/300"},
          {"name":"--context-foreground-blue-on-blue-selected","leafName":"on-blue-selected","light":"#2757C3","dark":"#2757C3","lightAlias":"Blue/600","darkAlias":"Blue/600"},
          {"name":"--context-foreground-blue-on-blue-disabled","leafName":"on-blue-disabled","light":"#A6C4F9","dark":"#084298","lightAlias":"Blue/200","darkAlias":"Blue/700"},
        ],
      },
    ],
  },
  {
    id: "background",
    title: "Background",
    description: "표면·중립 배경 색상.",
    sections: [
      {
        id: "context-background-surface",
        path: "Context/Background/Surface",
        tokens: [
          {"name":"--context-background-surface-bg-surface-quarernary","leafName":"bg-surface-quarernary","light":"#D7D8DC","dark":"#565967","lightAlias":"Gray/100","darkAlias":"Gray/500"},
          {"name":"--context-background-surface-bg-surface-teriary","leafName":"bg-surface-teriary","light":"#ECECEE","dark":"#434551","lightAlias":"Gray/50","darkAlias":"Gray/600"},
          {"name":"--context-background-surface-bg-surface-secondary","leafName":"bg-surface-secondary","light":"#F4F4F5","dark":"#33343D","lightAlias":"Gray/25","darkAlias":"Gray/700"},
          {"name":"--context-background-surface-bg-surface-base","leafName":"bg-surface-base","light":"#FFFFFF","dark":"#26282E","lightAlias":"Gray/White","darkAlias":"Gray/800"},
          {"name":"--context-background-surface-bg-surface-base-hover","leafName":"bg-surface-base-hover","light":"#ECECEE","dark":"#26282E","lightAlias":"Gray/50","darkAlias":"Gray/800"},
          {"name":"--context-background-surface-bg-surface-base-disabled","leafName":"bg-surface-base-disabled","light":"#F4F4F5","dark":"#33343D","lightAlias":"Gray/25","darkAlias":"Gray/700"},
          {"name":"--context-background-surface-bg-surface-base-selected","leafName":"bg-surface-base-selected","light":"#F4F4F5","dark":"#1F2025","lightAlias":"Gray/25","darkAlias":"Gray/850"},
          {"name":"--context-background-surface-bgbackdrop-dark","leafName":"BgBackdrop_Dark","light":"#1F2025","dark":"#1F2025","lightAlias":"Gray/850","darkAlias":"Gray/850"},
          {"name":"--context-background-surface-bg-surface-white","leafName":"bg-surface-white","light":"#FFFFFF","dark":"#141518","lightAlias":"Gray/White","darkAlias":"Gray/900"},
        ],
      },
      {
        id: "context-background-neutral",
        path: "Context/Background/Neutral",
        tokens: [
          {"name":"--context-background-neutral-bg-neutral-quarernary","leafName":"bg-neutral-quarernary","light":"#D7D8DC","dark":"#D7D8DC","lightAlias":"Gray/100","darkAlias":"Gray/100"},
          {"name":"--context-background-neutral-bg-neutral-teriary","leafName":"bg-neutral-teriary","light":"#ECECEE","dark":"#ECECEE","lightAlias":"Gray/50","darkAlias":"Gray/50"},
          {"name":"--context-background-neutral-bg-neutral-secondary","leafName":"bg-neutral-secondary","light":"#F4F4F5","dark":"#F4F4F5","lightAlias":"Gray/25","darkAlias":"Gray/25"},
          {"name":"--context-background-neutral-bg-neutral","leafName":"bg-neutral","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Gray/White","darkAlias":"Gray/White"},
          {"name":"--context-background-neutral-bg-neutral-hover","leafName":"bg-neutral-hover","light":"#F4F4F5","dark":"#F4F4F5","lightAlias":"Gray/25","darkAlias":"Gray/25"},
          {"name":"--context-background-neutral-bg-neutral-quarernary-hover","leafName":"bg-neutral-quarernary-hover","light":"#9698A3","dark":"#9698A3","lightAlias":"Gray/300","darkAlias":"Gray/300"},
          {"name":"--context-background-neutral-bg-neutral-disabled","leafName":"bg-neutral-disabled","light":"#F4F4F5","dark":"#F4F4F5","lightAlias":"Gray/25","darkAlias":"Gray/25"},
        ],
      },
      {
        id: "context-background-primary",
        path: "Context/Background/Primary",
        tokens: [
          {"name":"--context-background-primary-bg-primary","leafName":"bg-primary","light":"#7EF2F1","dark":"#9EF7EE","lightAlias":"Mint/500","darkAlias":"Mint/400"},
          {"name":"--context-background-primary-bg-primary-secondary","leafName":"bg-primary-secondary","light":"#B2FBED","dark":"#5CC7D0","lightAlias":"Mint/300","darkAlias":"Mint/600"},
          {"name":"--context-background-primary-bg-primary-hover","leafName":"bg-primary-hover","light":"#5CC7D0","dark":"#B2FBED","lightAlias":"Mint/600","darkAlias":"Mint/300"},
          {"name":"--context-background-primary-bg-primary-selectedhover","leafName":"bg-primary-selectedhover","light":"#28738C","dark":"#CDFDF0","lightAlias":"Mint/800","darkAlias":"Mint/200"},
          {"name":"--context-background-primary-bg-primary-disabled","leafName":"bg-primary-disabled","light":"#D5F2F1","dark":"#185474","lightAlias":null,"darkAlias":"Mint/900"},
        ],
      },
      {
        id: "context-background-gray",
        path: "Context/Background/Gray",
        tokens: [
          {"name":"--context-background-gray-bg-gray","leafName":"bg-gray","light":"#787A88","dark":"#565967","lightAlias":"Gray/400","darkAlias":"Gray/500"},
          {"name":"--context-background-gray-bg-darkgray","leafName":"bg-darkgray","light":"#33343D","dark":"#D7D8DC","lightAlias":"Gray/700","darkAlias":"Gray/100"},
          {"name":"--context-background-gray-bg-gray-hover","leafName":"bg-gray-hover","light":"#434551","dark":"#9698A3","lightAlias":"Gray/600","darkAlias":"Gray/300"},
          {"name":"--context-background-gray-bg-darkgray-hover","leafName":"bg-darkgray-hover","light":"#26282E","dark":"#565967","lightAlias":"Gray/800","darkAlias":"Gray/500"},
          {"name":"--context-background-gray-bg-gray-selectedhover","leafName":"bg-gray-selectedhover","light":"#33343D","dark":"#B3B4BC","lightAlias":"Gray/700","darkAlias":"Gray/200"},
          {"name":"--context-background-gray-bg-gray-disabled","leafName":"bg-gray-disabled","light":"#9698A3","dark":"#434551","lightAlias":"Gray/300","darkAlias":"Gray/600"},
        ],
      },
      {
        id: "context-background-error",
        path: "Context/Background/Error",
        tokens: [
          {"name":"--context-background-error-bg-error","leafName":"bg-error","light":"#FF312E","dark":"#FF5A58","lightAlias":"Red/500","darkAlias":"Red/400"},
          {"name":"--context-background-error-bg-error-hover","leafName":"bg-error-hover","light":"#CC2725","dark":"#FF8382","lightAlias":"Red/600","darkAlias":"Red/300"},
          {"name":"--context-background-error-bg-error-selectedhover","leafName":"bg-error-selectedhover","light":"#991D1C","dark":"#FFADAB","lightAlias":"Red/700","darkAlias":"Red/200"},
          {"name":"--context-background-error-bg-error-disabled","leafName":"bg-error-disabled","light":"#FFECEC","dark":"#661412","lightAlias":"Red/50","darkAlias":"Red/800"},
        ],
      },
      {
        id: "context-background-warning",
        path: "Context/Background/Warning",
        tokens: [
          {"name":"--context-background-warning-bg-warning","leafName":"bg-warning","light":"#FF8F0E","dark":"#FF8F0E","lightAlias":"Orange/500","darkAlias":"Orange/500"},
          {"name":"--context-background-warning-bg-warning-hover","leafName":"bg-warning-hover","light":"#CC720B","dark":"#FFA53E","lightAlias":"Orange/600","darkAlias":"Orange/400"},
          {"name":"--context-background-warning-bg-warning-selectedhover","leafName":"bg-warning-selectedhover","light":"#995608","dark":"#FFC787","lightAlias":"Orange/700","darkAlias":"Orange/200"},
          {"name":"--context-background-warning-bg-warning-disabled","leafName":"bg-warning-disabled","light":"#FFF1E0","dark":"#995608","lightAlias":"Orange/50","darkAlias":"Orange/700"},
        ],
      },
      {
        id: "context-background-success",
        path: "Context/Background/Success",
        tokens: [
          {"name":"--context-background-success-bg-success","leafName":"bg-success","light":"#09B200","dark":"#09B200","lightAlias":"Green/500","darkAlias":"Green/500"},
          {"name":"--context-background-success-bg-success-hover","leafName":"bg-success-hover","light":"#056B00","dark":"#84D980","lightAlias":"Green/700","darkAlias":"Green/300"},
          {"name":"--context-background-success-bg-success-selectedhover","leafName":"bg-success-selectedhover","light":"#044700","dark":"#A9E4A6","lightAlias":"Green/800","darkAlias":"Green/200"},
          {"name":"--context-background-success-bg-success-disabled","leafName":"bg-success-disabled","light":"#E9F8E8","dark":"#078E00","lightAlias":"Green/50","darkAlias":"Green/600"},
        ],
      },
      {
        id: "context-background-progress",
        path: "Context/Background/Progress",
        tokens: [
          {"name":"--context-background-progress-bg-progress","leafName":"bg-progress","light":"#0DCAF0","dark":"#0DCAF0","lightAlias":"Cyan/500","darkAlias":"Cyan/500"},
          {"name":"--context-background-progress-bg-progress-hover","leafName":"bg-progress-hover","light":"#0AA2C0","dark":"#6EDFF6","lightAlias":"Cyan/600","darkAlias":"Cyan/300"},
          {"name":"--context-background-progress-bg-progress-selectedhover","leafName":"bg-progress-selectedhover","light":"#0D6A7D","dark":"#9EEAF9","lightAlias":"Cyan/700","darkAlias":"Cyan/200"},
          {"name":"--context-background-progress-bg-progress-disabled","leafName":"bg-progress-disabled","light":"#E7FBFF","dark":"#064855","lightAlias":"Cyan/50","darkAlias":"Cyan/800"},
        ],
      },
      {
        id: "context-background-backdrop",
        path: "Context/Background/Backdrop",
        tokens: [
          {"name":"--context-background-backdrop-bgbackboard","leafName":"BgBackboard","light":"#F4F7F7","dark":"#1F2025","lightAlias":null,"darkAlias":"Gray/850"},
        ],
      },
    ],
  },
  {
    id: "tint",
    title: "Tint",
    description: "시맨틱 톤의 옅은 배경 팔레트.",
    sections: [
      {
        id: "context-background-tint",
        path: "Context/Background/Tint",
        tokens: [
          {"name":"--context-background-tint-bg-primary-tint","leafName":"bg-primary-tint","light":"#E5FEF5","dark":"#28738C","lightAlias":"Mint/100","darkAlias":"Mint/800"},
          {"name":"--context-background-tint-bg-primary-tint-hover","leafName":"bg-primary-tint-hover","light":"#CDFDF0","dark":"#3F9BAE","lightAlias":"Mint/200","darkAlias":"Mint/700"},
          {"name":"--context-background-tint-bg-primary-tint-selected","leafName":"bg-primary-tint-selected","light":"#CDFDF0","dark":"#28738C","lightAlias":"Mint/200","darkAlias":"Mint/800"},
          {"name":"--context-background-tint-bg-gray-tint","leafName":"bg-gray-tint","light":"#F4F4F5","dark":"#26282E","lightAlias":"Gray/25","darkAlias":"Gray/800"},
          {"name":"--context-background-tint-bg-gray-tint-hover","leafName":"bg-gray-tint-hover","light":"#ECECEE","dark":"#434551","lightAlias":"Gray/50","darkAlias":"Gray/600"},
          {"name":"--context-background-tint-bg-gray-tint-selected","leafName":"bg-gray-tint-selected","light":"#F4F4F5","dark":"#26282E","lightAlias":"Gray/25","darkAlias":"Gray/800"},
          {"name":"--context-background-tint-bg-purple-tint","leafName":"bg-purple-tint","light":"#F6EBFF","dark":"#3C0C66","lightAlias":"Purple/50","darkAlias":"Purple/800"},
          {"name":"--context-background-tint-bg-purple-tint-hover","leafName":"bg-purple-tint-hover","light":"#EAD2FF","dark":"#5B1299","lightAlias":"Purple/100","darkAlias":"Purple/700"},
          {"name":"--context-background-tint-bg-purple-tint-selected","leafName":"bg-purple-tint-selected","light":"#F6EBFF","dark":"#3C0C66","lightAlias":"Purple/50","darkAlias":"Purple/800"},
          {"name":"--context-background-tint-bg-red-tint","leafName":"bg-red-tint","light":"#FFECEC","dark":"#661412","lightAlias":"Red/50","darkAlias":"Red/800"},
          {"name":"--context-background-tint-bg-red-tint-hover","leafName":"bg-red-tint-hover","light":"#FFD6D5","dark":"#991D1C","lightAlias":"Red/100","darkAlias":"Red/700"},
          {"name":"--context-background-tint-bg-red-tint-selected","leafName":"bg-red-tint-selected","light":"#FFECEC","dark":"#661412","lightAlias":"Red/50","darkAlias":"Red/800"},
          {"name":"--context-background-tint-bg-green-tint","leafName":"bg-green-tint","light":"#E9F8E8","dark":"#044700","lightAlias":"Green/50","darkAlias":"Green/800"},
          {"name":"--context-background-tint-bg-green-tint-hover","leafName":"bg-green-tint-hover","light":"#CEF0CC","dark":"#056B00","lightAlias":"Green/100","darkAlias":"Green/700"},
          {"name":"--context-background-tint-bg-green-tint-selected","leafName":"bg-green-tint-selected","light":"#E9F8E8","dark":"#044700","lightAlias":"Green/50","darkAlias":"Green/800"},
          {"name":"--context-background-tint-bg-orange-tint","leafName":"bg-orange-tint","light":"#FFF1E0","dark":"#663906","lightAlias":"Orange/50","darkAlias":"Orange/800"},
          {"name":"--context-background-tint-bg-orange-tint-hover","leafName":"bg-orange-tint-hover","light":"#FFDDB6","dark":"#995608","lightAlias":"Orange/100","darkAlias":"Orange/700"},
          {"name":"--context-background-tint-bg-orange-tint-selected","leafName":"bg-orange-tint-selected","light":"#FFF1E0","dark":"#663906","lightAlias":"Orange/50","darkAlias":"Orange/800"},
          {"name":"--context-background-tint-bg-pink-tint","leafName":"bg-pink-tint","light":"#FEECFE","dark":"#601260","lightAlias":"Pink/50","darkAlias":"Pink/800"},
          {"name":"--context-background-tint-bg-pink-tint-hover","leafName":"bg-pink-tint-hover","light":"#FCD5FC","dark":"#901C90","lightAlias":"Pink/100","darkAlias":"Pink/700"},
          {"name":"--context-background-tint-bg-pink-tint-selected","leafName":"bg-pink-tint-selected","light":"#FEECFE","dark":"#601260","lightAlias":"Pink/50","darkAlias":"Pink/800"},
          {"name":"--context-background-tint-bg-yellow-tint","leafName":"bg-yellow-tint","light":"#FFF8E0","dark":"#664F05","lightAlias":"Yellow/50","darkAlias":"Yellow/800"},
          {"name":"--context-background-tint-bg-yellow-tint-hover","leafName":"bg-yellow-tint-hover","light":"#FFEEB6","dark":"#997707","lightAlias":"Yellow/100","darkAlias":"Yellow/700"},
          {"name":"--context-background-tint-bg-yellow-tint-selected","leafName":"bg-yellow-tint-selected","light":"#FFF8E0","dark":"#664F05","lightAlias":"Yellow/50","darkAlias":"Yellow/800"},
          {"name":"--context-background-tint-bg-cyan-tint","leafName":"bg-cyan-tint","light":"#E7FBFF","dark":"#064855","lightAlias":"Cyan/50","darkAlias":"Cyan/800"},
          {"name":"--context-background-tint-bg-cyan-tint-hover","leafName":"bg-cyan-tint-hover","light":"#CFF4FC","dark":"#0D6A7D","lightAlias":"Cyan/100","darkAlias":"Cyan/700"},
          {"name":"--context-background-tint-bg-cyan-tint-selected","leafName":"bg-cyan-tint-selected","light":"#E7FBFF","dark":"#064855","lightAlias":"Cyan/50","darkAlias":"Cyan/800"},
          {"name":"--context-background-tint-bg-blue-tint","leafName":"bg-blue-tint","light":"#E7F1FF","dark":"#052C65","lightAlias":"Blue/50","darkAlias":"Blue/800"},
          {"name":"--context-background-tint-bg-blue-tint-hover","leafName":"bg-blue-tint-hover","light":"#CAE0FF","dark":"#084298","lightAlias":"Blue/100","darkAlias":"Blue/700"},
          {"name":"--context-background-tint-bg-blue-tint-selected","leafName":"bg-blue-tint-selected","light":"#E7F1FF","dark":"#052C65","lightAlias":"Blue/50","darkAlias":"Blue/800"},
          {"name":"--context-background-tint-bg-magenta-tint","leafName":"bg-magenta-tint","light":"#FFF0F5","dark":"#8C0052","lightAlias":"Magenta/50","darkAlias":"Magenta/800"},
          {"name":"--context-background-tint-bg-magenta-tint-hover","leafName":"bg-magenta-tint-hover","light":"#FFC7DB","dark":"#B30765","lightAlias":"Magenta/100","darkAlias":"Magenta/700"},
          {"name":"--context-background-tint-bg-magenta-tint-selected","leafName":"bg-magenta-tint-selected","light":"#FFF0F5","dark":"#8C0052","lightAlias":"Magenta/50","darkAlias":"Magenta/800"},
          {"name":"--context-background-tint-bg-gold-tint","leafName":"bg-gold-tint","light":"#F0EFE1","dark":"#3D2900","lightAlias":"Gold/50","darkAlias":"Gold/800"},
          {"name":"--context-background-tint-bg-gold-tint-hover","leafName":"bg-gold-tint-hover","light":"#E3DEB1","dark":"#634704","lightAlias":"Gold/100","darkAlias":"Gold/700"},
          {"name":"--context-background-tint-bg-gold-tint-selected","leafName":"bg-gold-tint-selected","light":"#F0EFE1","dark":"#3D2900","lightAlias":"Gold/50","darkAlias":"Gold/800"},
        ],
      },
    ],
  },
  {
    id: "accent",
    title: "Accent",
    description: "컬러별 액센트 스케일.",
    sections: [
      {
        id: "accent-gray",
        path: "Accent/Gray",
        tokens: [
          {"name":"--accent-gray-accent-gray-tint","leafName":"accent-gray-tint","light":"#ECECEE","dark":"#ECECEE","lightAlias":"Gray/50","darkAlias":"Gray/50"},
          {"name":"--accent-gray-accent-gray-lightest","leafName":"accent-gray-lightest","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
          {"name":"--accent-gray-accent-gray-light","leafName":"accent-gray-light","light":"#9698A3","dark":"#9698A3","lightAlias":"Gray/300","darkAlias":"Gray/300"},
          {"name":"--accent-gray-accent-gray","leafName":"accent-gray","light":"#787A88","dark":"#787A88","lightAlias":"Gray/400","darkAlias":"Gray/400"},
          {"name":"--accent-gray-accent-gray-dark","leafName":"accent-gray-dark","light":"#434551","dark":"#434551","lightAlias":"Gray/600","darkAlias":"Gray/600"},
          {"name":"--accent-gray-accent-gray-darkest","leafName":"accent-gray-darkest","light":"#1F2025","dark":"#33343D","lightAlias":"Gray/850","darkAlias":"Gray/700"},
        ],
      },
      {
        id: "accent-teal",
        path: "Accent/Teal",
        tokens: [
          {"name":"--accent-teal-accent-teal-tint","leafName":"accent-teal-tint","light":"#D2F4EA","dark":"#E6F6F1","lightAlias":"Teal/100","darkAlias":"Teal/50"},
          {"name":"--accent-teal-accent-teal-lightest","leafName":"accent-teal-lightest","light":"#A6E9D5","dark":"#D2F4EA","lightAlias":"Teal/200","darkAlias":"Teal/100"},
          {"name":"--accent-teal-accent-teal-light","leafName":"accent-teal-light","light":"#4DD4AC","dark":"#79DFC1","lightAlias":"Teal/400","darkAlias":"Teal/300"},
          {"name":"--accent-teal-accent-teal","leafName":"accent-teal","light":"#20C997","dark":"#4DD4AC","lightAlias":"Teal/500","darkAlias":"Teal/400"},
          {"name":"--accent-teal-accent-teal-dark","leafName":"accent-teal-dark","light":"#13795B","dark":"#1AA179","lightAlias":"Teal/700","darkAlias":"Teal/600"},
          {"name":"--accent-teal-accent-teal-darkest","leafName":"accent-teal-darkest","light":"#0D503C","dark":"#13795B","lightAlias":"Teal/800","darkAlias":"Teal/700"},
        ],
      },
      {
        id: "accent-purple",
        path: "Accent/Purple",
        tokens: [
          {"name":"--accent-purple-accent-purple-tint","leafName":"accent-purple-tint","light":"#EAD2FF","dark":"#F6EBFF","lightAlias":"Purple/100","darkAlias":"Purple/50"},
          {"name":"--accent-purple-accent-purple-lightest","leafName":"accent-purple-lightest","light":"#D5A5FF","dark":"#EAD2FF","lightAlias":"Purple/200","darkAlias":"Purple/100"},
          {"name":"--accent-purple-accent-purple-light","leafName":"accent-purple-light","light":"#AC4BFF","dark":"#C178FF","lightAlias":"Purple/400","darkAlias":"Purple/300"},
          {"name":"--accent-purple-accent-purple","leafName":"accent-purple","light":"#971EFF","dark":"#AC4BFF","lightAlias":"Purple/500","darkAlias":"Purple/400"},
          {"name":"--accent-purple-accent-purple-dark","leafName":"accent-purple-dark","light":"#5B1299","dark":"#7918CC","lightAlias":"Purple/700","darkAlias":"Purple/600"},
          {"name":"--accent-purple-accent-purple-darkest","leafName":"accent-purple-darkest","light":"#3C0C66","dark":"#5B1299","lightAlias":"Purple/800","darkAlias":"Purple/700"},
        ],
      },
      {
        id: "accent-red",
        path: "Accent/Red",
        tokens: [
          {"name":"--accent-red-accent-red-tint","leafName":"accent-red-tint","light":"#FFD6D5","dark":"#FFECEC","lightAlias":"Red/100","darkAlias":"Red/50"},
          {"name":"--accent-red-accent-red-lightest","leafName":"accent-red-lightest","light":"#FFADAB","dark":"#FFD6D5","lightAlias":"Red/200","darkAlias":"Red/100"},
          {"name":"--accent-red-accent-red-light","leafName":"accent-red-light","light":"#FF5A58","dark":"#FF8382","lightAlias":"Red/400","darkAlias":"Red/300"},
          {"name":"--accent-red-accent-red","leafName":"accent-red","light":"#FF312E","dark":"#FF5A58","lightAlias":"Red/500","darkAlias":"Red/400"},
          {"name":"--accent-red-accent-red-dark","leafName":"accent-red-dark","light":"#991D1C","dark":"#CC2725","lightAlias":"Red/700","darkAlias":"Red/600"},
          {"name":"--accent-red-accent-red-darkest","leafName":"accent-red-darkest","light":"#661412","dark":"#991D1C","lightAlias":"Red/800","darkAlias":"Red/700"},
        ],
      },
      {
        id: "accent-pink",
        path: "Accent/Pink",
        tokens: [
          {"name":"--accent-pink-accent-pink-tint","leafName":"accent-pink-tint","light":"#FCD5FC","dark":"#FEECFE","lightAlias":"Pink/100","darkAlias":"Pink/50"},
          {"name":"--accent-pink-accent-pink-lightest","leafName":"accent-pink-lightest","light":"#F9ABF9","dark":"#FCD5FC","lightAlias":"Pink/200","darkAlias":"Pink/100"},
          {"name":"--accent-pink-accent-pink-light","leafName":"accent-pink-light","light":"#F358F3","dark":"#F682F6","lightAlias":"Pink/400","darkAlias":"Pink/300"},
          {"name":"--accent-pink-accent-pink","leafName":"accent-pink","light":"#F02EF0","dark":"#F358F3","lightAlias":"Pink/500","darkAlias":"Pink/400"},
          {"name":"--accent-pink-accent-pink-dark","leafName":"accent-pink-dark","light":"#901C90","dark":"#C025C0","lightAlias":"Pink/700","darkAlias":"Pink/600"},
          {"name":"--accent-pink-accent-pink-darkest","leafName":"accent-pink-darkest","light":"#601260","dark":"#901C90","lightAlias":"Pink/800","darkAlias":"Pink/700"},
        ],
      },
      {
        id: "accent-yellow",
        path: "Accent/Yellow",
        tokens: [
          {"name":"--accent-yellow-accent-yellow-tint","leafName":"accent-yellow-tint","light":"#FFEEB6","dark":"#FFF8E0","lightAlias":"Yellow/100","darkAlias":"Yellow/50"},
          {"name":"--accent-yellow-accent-yellow-lightest","leafName":"accent-yellow-lightest","light":"#FFE386","dark":"#FFEEB6","lightAlias":"Yellow/200","darkAlias":"Yellow/100"},
          {"name":"--accent-yellow-accent-yellow-light","leafName":"accent-yellow-light","light":"#FFD13D","dark":"#FFDA61","lightAlias":"Yellow/400","darkAlias":"Yellow/300"},
          {"name":"--accent-yellow-accent-yellow","leafName":"accent-yellow","light":"#FFC60C","dark":"#FFD13D","lightAlias":"Yellow/500","darkAlias":"Yellow/400"},
          {"name":"--accent-yellow-accent-yellow-dark","leafName":"accent-yellow-dark","light":"#997707","dark":"#CC9E0A","lightAlias":"Yellow/700","darkAlias":"Yellow/600"},
          {"name":"--accent-yellow-accent-yellow-darkest","leafName":"accent-yellow-darkest","light":"#664F05","dark":"#997707","lightAlias":"Yellow/800","darkAlias":"Yellow/700"},
        ],
      },
      {
        id: "accent-green",
        path: "Accent/Green",
        tokens: [
          {"name":"--accent-green-accent-green-tint","leafName":"accent-green-tint","light":"#CEF0CC","dark":"#E9F8E8","lightAlias":"Green/100","darkAlias":"Green/50"},
          {"name":"--accent-green-accent-green-lightest","leafName":"accent-green-lightest","light":"#A9E4A6","dark":"#CEF0CC","lightAlias":"Green/200","darkAlias":"Green/100"},
          {"name":"--accent-green-accent-green-light","leafName":"accent-green-light","light":"#3AC133","dark":"#84D980","lightAlias":"Green/400","darkAlias":"Green/300"},
          {"name":"--accent-green-accent-green","leafName":"accent-green","light":"#09B200","dark":"#3AC133","lightAlias":"Green/500","darkAlias":"Green/400"},
          {"name":"--accent-green-accent-green-dark","leafName":"accent-green-dark","light":"#056B00","dark":"#078E00","lightAlias":"Green/700","darkAlias":"Green/600"},
          {"name":"--accent-green-accent-green-darkest","leafName":"accent-green-darkest","light":"#044700","dark":"#056B00","lightAlias":"Green/800","darkAlias":"Green/700"},
        ],
      },
      {
        id: "accent-cyan",
        path: "Accent/Cyan",
        tokens: [
          {"name":"--accent-cyan-accent-cyan-tint","leafName":"accent-cyan-tint","light":"#CFF4FC","dark":"#E7FBFF","lightAlias":"Cyan/100","darkAlias":"Cyan/50"},
          {"name":"--accent-cyan-accent-cyan-lightest","leafName":"accent-cyan-lightest","light":"#9EEAF9","dark":"#CFF4FC","lightAlias":"Cyan/200","darkAlias":"Cyan/100"},
          {"name":"--accent-cyan-accent-cyan-light","leafName":"accent-cyan-light","light":"#3DD5F3","dark":"#6EDFF6","lightAlias":"Cyan/400","darkAlias":"Cyan/300"},
          {"name":"--accent-cyan-accent-cyan","leafName":"accent-cyan","light":"#0AA2C0","dark":"#3DD5F3","lightAlias":"Cyan/600","darkAlias":"Cyan/400"},
          {"name":"--accent-cyan-accent-cyan-dark","leafName":"accent-cyan-dark","light":"#0D6A7D","dark":"#0AA2C0","lightAlias":"Cyan/700","darkAlias":"Cyan/600"},
          {"name":"--accent-cyan-accent-cyan-darkest","leafName":"accent-cyan-darkest","light":"#064855","dark":"#0D6A7D","lightAlias":"Cyan/800","darkAlias":"Cyan/700"},
        ],
      },
      {
        id: "accent-orange",
        path: "Accent/Orange",
        tokens: [
          {"name":"--accent-orange-accent-orange-tint","leafName":"accent-orange-tint","light":"#FFDDB6","dark":"#FFF1E0","lightAlias":"Orange/100","darkAlias":"Orange/50"},
          {"name":"--accent-orange-accent-orange-lightest","leafName":"accent-orange-lightest","light":"#FFC787","dark":"#FFDDB6","lightAlias":"Orange/200","darkAlias":"Orange/100"},
          {"name":"--accent-orange-accent-orange-light","leafName":"accent-orange-light","light":"#FFA53E","dark":"#FFBC6E","lightAlias":"Orange/400","darkAlias":"Orange/300"},
          {"name":"--accent-orange-accent-orange","leafName":"accent-orange","light":"#FF8F0E","dark":"#FFA53E","lightAlias":"Orange/500","darkAlias":"Orange/400"},
          {"name":"--accent-orange-accent-orange-dark","leafName":"accent-orange-dark","light":"#995608","dark":"#CC720B","lightAlias":"Orange/700","darkAlias":"Orange/600"},
          {"name":"--accent-orange-accent-orange-darkest","leafName":"accent-orange-darkest","light":"#663906","dark":"#995608","lightAlias":"Orange/800","darkAlias":"Orange/700"},
        ],
      },
      {
        id: "accent-blue",
        path: "Accent/Blue",
        tokens: [
          {"name":"--accent-blue-accent-blue-tint","leafName":"accent-blue-tint","light":"#CAE0FF","dark":"#E7F1FF","lightAlias":"Blue/100","darkAlias":"Blue/50"},
          {"name":"--accent-blue-accent-blue-lightest","leafName":"accent-blue-lightest","light":"#A6C4F9","dark":"#CAE0FF","lightAlias":"Blue/200","darkAlias":"Blue/100"},
          {"name":"--accent-blue-accent-blue-light","leafName":"accent-blue-light","light":"#5289F5","dark":"#5289F5","lightAlias":"Blue/400","darkAlias":"Blue/400"},
          {"name":"--accent-blue-accent-blue","leafName":"accent-blue","light":"#316CF4","dark":"#5289F5","lightAlias":"Blue/500","darkAlias":"Blue/400"},
          {"name":"--accent-blue-accent-blue-dark","leafName":"accent-blue-dark","light":"#084298","dark":"#316CF4","lightAlias":"Blue/700","darkAlias":"Blue/500"},
          {"name":"--accent-blue-accent-blue-darkest","leafName":"accent-blue-darkest","light":"#052C65","dark":"#084298","lightAlias":"Blue/800","darkAlias":"Blue/700"},
        ],
      },
      {
        id: "accent-magenta",
        path: "Accent/Magenta",
        tokens: [
          {"name":"--accent-magenta-accent-magenta-tint","leafName":"accent-magenta-tint","light":"#FFC7DB","dark":"#FFF0F5","lightAlias":"Magenta/100","darkAlias":"Magenta/50"},
          {"name":"--accent-magenta-accent-magenta-lightest","leafName":"accent-magenta-lightest","light":"#FF9EC3","dark":"#FFC7DB","lightAlias":"Magenta/200","darkAlias":"Magenta/100"},
          {"name":"--accent-magenta-accent-magenta-light","leafName":"accent-magenta-light","light":"#FF4D9D","dark":"#FF75AF","lightAlias":"Magenta/400","darkAlias":"Magenta/300"},
          {"name":"--accent-magenta-accent-magenta","leafName":"accent-magenta","light":"#FF248E","dark":"#FF4D9D","lightAlias":"Magenta/500","darkAlias":"Magenta/400"},
          {"name":"--accent-magenta-accent-magenta-dark","leafName":"accent-magenta-dark","light":"#B30765","dark":"#D91479","lightAlias":"Magenta/700","darkAlias":"Magenta/600"},
          {"name":"--accent-magenta-accent-magenta-darkest","leafName":"accent-magenta-darkest","light":"#8C0052","dark":"#B30765","lightAlias":"Magenta/800","darkAlias":"Magenta/700"},
        ],
      },
      {
        id: "accent-gold",
        path: "Accent/Gold",
        tokens: [
          {"name":"--accent-gold-accent-gold-tint","leafName":"accent-gold-tint","light":"#E3DEB1","dark":"#F0EFE1","lightAlias":"Gold/100","darkAlias":"Gold/50"},
          {"name":"--accent-gold-accent-gold-lightest","leafName":"accent-gold-lightest","light":"#D6CB85","dark":"#E3DEB1","lightAlias":"Gold/200","darkAlias":"Gold/100"},
          {"name":"--accent-gold-accent-gold-light","leafName":"accent-gold-light","light":"#BDA239","dark":"#C9B75D","lightAlias":"Gold/400","darkAlias":"Gold/300"},
          {"name":"--accent-gold-accent-gold","leafName":"accent-gold","light":"#AF8C19","dark":"#BDA239","lightAlias":"Gold/500","darkAlias":"Gold/400"},
          {"name":"--accent-gold-accent-gold-dark","leafName":"accent-gold-dark","light":"#634704","dark":"#8A680C","lightAlias":"Gold/700","darkAlias":"Gold/600"},
          {"name":"--accent-gold-accent-gold-darkest","leafName":"accent-gold-darkest","light":"#3D2900","dark":"#634704","lightAlias":"Gold/800","darkAlias":"Gold/700"},
        ],
      },
    ],
  },
  {
    id: "border",
    title: "Border",
    description: "시맨틱 보더 색상.",
    sections: [
      {
        id: "border",
        path: "Border",
        tokens: [
          {"name":"--border-border-primary","leafName":"border-primary","light":"#5CC7D0","dark":"#9EF7EE","lightAlias":"Mint/600","darkAlias":"Mint/400"},
          {"name":"--border-border-primary-hover","leafName":"border-Primary-hover","light":"#28738C","dark":"#5CC7D0","lightAlias":"Mint/800","darkAlias":"Mint/600"},
          {"name":"--border-border-valid","leafName":"border-valid","light":"#3AC133","dark":"#3AC133","lightAlias":"Green/400","darkAlias":"Green/400"},
          {"name":"--border-border-invalid","leafName":"border-invalid","light":"#FF5A58","dark":"#FF5A58","lightAlias":"Red/400","darkAlias":"Red/400"},
          {"name":"--border-border-gray-tint","leafName":"border-gray-tint","light":"#D7D8DC","dark":"#D7D8DC","lightAlias":"Gray/100","darkAlias":"Gray/100"},
          {"name":"--border-border-purple-tint","leafName":"border-purple-tint","light":"#EAD2FF","dark":"#5B1299","lightAlias":"Purple/100","darkAlias":"Purple/700"},
          {"name":"--border-border-pink-tint","leafName":"border-pink-tint","light":"#FCD5FC","dark":"#901C90","lightAlias":"Pink/100","darkAlias":"Pink/700"},
          {"name":"--border-border-red-tint","leafName":"border-red-tint","light":"#FFD6D5","dark":"#991D1C","lightAlias":"Red/100","darkAlias":"Red/700"},
          {"name":"--border-border-green-tint","leafName":"border-green-tint","light":"#CEF0CC","dark":"#056B00","lightAlias":"Green/100","darkAlias":"Green/700"},
          {"name":"--border-border-yellow-tint","leafName":"border-yellow-tint","light":"#FFEEB6","dark":"#997707","lightAlias":"Yellow/100","darkAlias":"Yellow/700"},
          {"name":"--border-border-orange-tint","leafName":"border-orange-tint","light":"#FFDDB6","dark":"#995608","lightAlias":"Orange/100","darkAlias":"Orange/700"},
          {"name":"--border-border-cyan-tint","leafName":"border-cyan-tint","light":"#CFF4FC","dark":"#0D6A7D","lightAlias":"Cyan/100","darkAlias":"Cyan/700"},
          {"name":"--border-border-blue-tint","leafName":"border-blue-tint","light":"#CAE0FF","dark":"#084298","lightAlias":"Blue/100","darkAlias":"Blue/700"},
          {"name":"--border-border-teal-tint","leafName":"border-teal-tint","light":"#D2F4EA","dark":"#13795B","lightAlias":"Teal/100","darkAlias":"Teal/700"},
          {"name":"--border-border-magenta-tint","leafName":"border-magenta-tint","light":"#FFC7DB","dark":"#B30765","lightAlias":"Magenta/100","darkAlias":"Magenta/700"},
          {"name":"--border-border-gold-tint","leafName":"border-gold-tint","light":"#E3DEB1","dark":"#634704","lightAlias":"Gold/100","darkAlias":"Gold/700"},
        ],
      },
    ],
  },
  {
    id: "borderNeutral",
    title: "Border · Neutral",
    description: "중립 보더 스케일.",
    sections: [
      {
        id: "border-neutral",
        path: "Border/Neutral",
        tokens: [
          {"name":"--border-neutral-border-neutral-white","leafName":"border-neutral-white","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Gray/White","darkAlias":"Gray/White"},
          {"name":"--border-neutral-border-neutral-quaternary","leafName":"border-neutral-quaternary","light":"#9698A3","dark":"#9698A3","lightAlias":"Gray/300","darkAlias":"Gray/300"},
          {"name":"--border-neutral-border-neutral-tertiary","leafName":"border-neutral-tertiary","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
          {"name":"--border-neutral-border-neutral-secondary-hover","leafName":"border-neutral-secondary-hover","light":"#D7D8DC","dark":"#D7D8DC","lightAlias":"Gray/100","darkAlias":"Gray/100"},
          {"name":"--border-neutral-border-neutral-secondary","leafName":"border-neutral-secondary","light":"#ECECEE","dark":"#ECECEE","lightAlias":"Gray/50","darkAlias":"Gray/50"},
          {"name":"--border-neutral-border-neutral","leafName":"border-neutral","light":"#D7D8DC","dark":"#D7D8DC","lightAlias":"Gray/100","darkAlias":"Gray/100"},
          {"name":"--border-neutral-border-neutral-hover","leafName":"border-neutral-hover","light":"#B3B4BC","dark":"#B3B4BC","lightAlias":"Gray/200","darkAlias":"Gray/200"},
          {"name":"--border-neutral-border-neutral-disabled","leafName":"border-neutral-disabled","light":"#D7D8DC","dark":"#D7D8DC","lightAlias":"Gray/100","darkAlias":"Gray/100"},
          {"name":"--border-neutral-border-neutral-darkest","leafName":"border-neutral-darkest","light":"#26282E","dark":"#26282E","lightAlias":"Gray/800","darkAlias":"Gray/800"},
          {"name":"--border-neutral-border-neutral-dark","leafName":"border-neutral-dark","light":"#434551","dark":"#434551","lightAlias":"Gray/600","darkAlias":"Gray/600"},
        ],
      },
    ],
  },
  {
    id: "borderSurface",
    title: "Border · Surface",
    description: "Surface 레이어용 보더.",
    sections: [
      {
        id: "border-border-surface",
        path: "Border/Border Surface",
        tokens: [
          {"name":"--border-border-surface-border-surface-white","leafName":"border-surface-white","light":"#FFFFFF","dark":"#000000","lightAlias":"Gray/White","darkAlias":"Gray/Black"},
          {"name":"--border-border-surface-border-surface","leafName":"border-surface","light":"#D7D8DC","dark":"#434551","lightAlias":"Gray/100","darkAlias":"Gray/600"},
          {"name":"--border-border-surface-border-surface-hover","leafName":"border-surface-Hover","light":"#B3B4BC","dark":"#434551","lightAlias":"Gray/200","darkAlias":"Gray/600"},
          {"name":"--border-border-surface-border-surface-quaternary","leafName":"border-surface-quaternary","light":"#9698A3","dark":"#565967","lightAlias":"Gray/300","darkAlias":"Gray/500"},
          {"name":"--border-border-surface-border-surface-tertiary","leafName":"border-surface-tertiary","light":"#B3B4BC","dark":"#434551","lightAlias":"Gray/200","darkAlias":"Gray/600"},
          {"name":"--border-border-surface-border-surface-secondary","leafName":"border-surface-secondary","light":"#ECECEE","dark":"#33343D","lightAlias":"Gray/50","darkAlias":"Gray/700"},
          {"name":"--border-border-surface-border-surface-disabled","leafName":"border-surface-disabled","light":"#D7D8DC","dark":"#33343D","lightAlias":"Gray/100","darkAlias":"Gray/700"},
          {"name":"--border-border-surface-border-surface-darkest","leafName":"border-surface-darkest","light":"#26282E","dark":"#565967","lightAlias":"Gray/800","darkAlias":"Gray/500"},
          {"name":"--border-border-surface-border-surface-lightest","leafName":"border-surface-lightest","light":"#FFFFFF","dark":"#33343D","lightAlias":"Gray/White","darkAlias":"Gray/700"},
        ],
      },
    ],
  },
  {
    id: "borderOpacity",
    title: "Border · Opacity",
    description: "반투명 보더 토큰.",
    sections: [
      {
        id: "border-opacityborder",
        path: "Border/OpacityBorder",
        tokens: [
          {"name":"--border-opacityborder-borderblackopacity10-2","leafName":"BorderBlackOpacity10 2","light":"#000000","dark":"#FFFFFF","lightAlias":null,"darkAlias":null},
          {"name":"--border-opacityborder-borderopacity70","leafName":"BorderOpacity70","light":"#ECECEE","dark":"#ECECEE","lightAlias":null,"darkAlias":null},
        ],
      },
    ],
  },
  {
    id: "opacity",
    title: "Opacity",
    description: "반투명 오버레이 컬러.",
    sections: [
      {
        id: "opacity",
        path: "Opacity",
        tokens: [
          {"name":"--opacity-surfacesecondary-70","leafName":"SurfaceSecondary_70","light":"#F4F4F5","dark":"#26282E","lightAlias":"Opacity/Grayscale/Gray25_70%","darkAlias":"Opacity/Grayscale/Gray800_70%"},
          {"name":"--opacity-opacitypanel","leafName":"OpacityPanel","light":"#FFFFFF","dark":"#26282E","lightAlias":"Opacity/Grayscale/White_50%","darkAlias":"Opacity/Grayscale/Gray800_70%"},
          {"name":"--opacity-surfacewhiteopacity-50","leafName":"SurfaceWhiteOpacity_50","light":"#FFFFFF","dark":"#000000","lightAlias":"Opacity/Grayscale/White_50%","darkAlias":"Opacity/Grayscale/Black_50%"},
          {"name":"--opacity-surfacewhiteopacity-70","leafName":"SurfaceWhiteOpacity_70","light":"#FFFFFF","dark":"#000000","lightAlias":"Opacity/Grayscale/White_70%","darkAlias":"Opacity/Grayscale/Black_70%"},
          {"name":"--opacity-surfaceblackopacity-8","leafName":"SurfaceBlackOpacity_8","light":"#000000","dark":"#FFFFFF","lightAlias":"Opacity/Grayscale/Black_8%","darkAlias":"Opacity/Grayscale/White_8%"},
          {"name":"--opacity-whiteopacity-8","leafName":"WhiteOpacity_8","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Opacity/Grayscale/White_8%","darkAlias":"Opacity/Grayscale/White_8%"},
          {"name":"--opacity-whiteopacity-50","leafName":"WhiteOpacity_50","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Opacity/Grayscale/White_50%","darkAlias":"Opacity/Grayscale/White_8%"},
          {"name":"--opacity-whiteopacity-70","leafName":"WhiteOpacity_70","light":"#FFFFFF","dark":"#FFFFFF","lightAlias":"Opacity/Grayscale/White_70%","darkAlias":"Opacity/Grayscale/White_50%"},
          {"name":"--opacity-blackopacity-8","leafName":"BlackOpacity_8","light":"#000000","dark":"#000000","lightAlias":"Opacity/Grayscale/Black_8%","darkAlias":"Opacity/Grayscale/Black_8%"},
          {"name":"--opacity-blackopacity-50","leafName":"BlackOpacity_50","light":"#000000","dark":"#000000","lightAlias":"Opacity/Grayscale/Black_50%","darkAlias":"Opacity/Grayscale/Black_70%"},
          {"name":"--opacity-blackopacity-90","leafName":"BlackOpacity_90","light":"#000000","dark":"#000000","lightAlias":"Opacity/Grayscale/Black_90%","darkAlias":"Opacity/Grayscale/Black_90%"},
          {"name":"--opacity-primaryopacity-8","leafName":"PrimaryOpacity_8","light":"#43C6C1","dark":"#43C6C1","lightAlias":"Opacity/Accent/Primary500_8%","darkAlias":"Opacity/Accent/Primary500_8%"},
          {"name":"--opacity-primaryopacity-15","leafName":"PrimaryOpacity_15","light":"#43C6C1","dark":"#43C6C1","lightAlias":"Opacity/Accent/Primary500_15%","darkAlias":"Opacity/Accent/Primary500_15%"},
          {"name":"--opacity-primaryopacity-20","leafName":"PrimaryOpacity_20","light":"#43C6C1","dark":"#43C6C1","lightAlias":"Opacity/Accent/Primary500_20%","darkAlias":"Opacity/Accent/Primary500_20%"},
          {"name":"--opacity-primaryopacity-25","leafName":"PrimaryOpacity_25","light":"#43C6C1","dark":"#43C6C1","lightAlias":"Opacity/Accent/Primary500_25%","darkAlias":"Opacity/Accent/Primary500_25%"},
          {"name":"--opacity-primaryopacity-30","leafName":"PrimaryOpacity_30","light":"#43C6C1","dark":"#43C6C1","lightAlias":"Opacity/Accent/Primary500_30%","darkAlias":"Opacity/Accent/Primary300_45%"},
          {"name":"--opacity-surfaceprimaryopacity-30","leafName":"SurfacePrimaryOpacity_30","light":"#43C6C1","dark":"#C178FF","lightAlias":"Opacity/Accent/Primary500_30%","darkAlias":null},
          {"name":"--opacity-blueopacity-30","leafName":"BlueOpacity_30","light":"#316CF4","dark":"#316CF4","lightAlias":"Opacity/Accent/Blue500_30%","darkAlias":"Opacity/Accent/Blue500_30%"},
          {"name":"--opacity-orangeopacity-15","leafName":"OrangeOpacity_15","light":"#FF8F0E","dark":"#FF8F0E","lightAlias":"Opacity/Accent/Orange500_15%","darkAlias":"Opacity/Accent/Orange500_15%"},
          {"name":"--opacity-cyanopacity-15","leafName":"CyanOpacity_15","light":"#0DCAF0","dark":"#0DCAF0","lightAlias":"Opacity/Accent/Cyan500_15%","darkAlias":"Opacity/Accent/Cyan500_15%"},
          {"name":"--opacity-cyanopacity-30","leafName":"CyanOpacity_30","light":"#0AA2C0","dark":"#0AA2C0","lightAlias":"Opacity/Accent/Cyan600_30%","darkAlias":"Opacity/Accent/Cyan600_30%"},
          {"name":"--opacity-pinkopacity-8","leafName":"PinkOpacity_8","light":"#F02EB6","dark":"#F02EB6","lightAlias":"Opacity/Accent/Pink500_15%","darkAlias":"Opacity/Accent/Pink500_15%"},
          {"name":"--opacity-pinkopacity-10","leafName":"PinkOpacity_10","light":"#F02EB6","dark":"#F02EB6","lightAlias":"Opacity/Accent/Pink500_10%","darkAlias":"Opacity/Accent/Pink500_10%"},
        ],
      },
    ],
  },
  {
    id: "bgTransparency",
    title: "BG · Transparency",
    description: "Alert 등에서 쓰는 반투명 배경 토큰.",
    sections: [
      {
        id: "bg-transparency",
        path: "bg Transparency",
        tokens: [
          {"name":"--bg-transparency-red","leafName":"red","light":"rgba(255, 236, 236, 0.5)","dark":"rgba(255, 236, 236, 0.5)","lightAlias":null,"darkAlias":null},
          {"name":"--bg-transparency-orange","leafName":"orange","light":"rgba(255, 241, 224, 0.5)","dark":"rgba(255, 241, 224, 0.5)","lightAlias":null,"darkAlias":null},
          {"name":"--bg-transparency-green","leafName":"green","light":"rgba(233, 248, 232, 0.5)","dark":"rgba(233, 248, 232, 0.5)","lightAlias":null,"darkAlias":null},
          {"name":"--bg-transparency-purple","leafName":"purple","light":"rgba(246, 235, 255, 0.5)","dark":"rgba(246, 235, 255, 0.5)","lightAlias":null,"darkAlias":null},
          {"name":"--bg-transparency-blue","leafName":"blue","light":"rgba(231, 241, 255, 0.5)","dark":"rgba(231, 241, 255, 0.5)","lightAlias":null,"darkAlias":null},
        ],
      },
    ],
  },
];
