// Auto-generated by scripts/generate-icon-catalog.js — do not edit directly.
// Run: npm run gen:icons

export type IconEntry = {
  /** File base name without extension */
  name: string;
  /** Folder grouping ("Default" for root level) */
  group: string;
  /** Public URL beneath /public */
  url: string;
  /** Lowercase searchable string */
  keywords: string;
};

export const ICON_ENTRIES: readonly IconEntry[] = [
  {
    "name": "Type=Ascending",
    "group": "Data Grid / Header",
    "url": "/icon/Data%20Grid/Header/Type%3DAscending.svg",
    "keywords": "type ascending data grid header"
  },
  {
    "name": "Type=Descending",
    "group": "Data Grid / Header",
    "url": "/icon/Data%20Grid/Header/Type%3DDescending.svg",
    "keywords": "type descending data grid header"
  },
  {
    "name": "Type=Editable",
    "group": "Data Grid / Header",
    "url": "/icon/Data%20Grid/Header/Type%3DEditable.svg",
    "keywords": "type editable data grid header"
  },
  {
    "name": "Type=Filter",
    "group": "Data Grid / Header",
    "url": "/icon/Data%20Grid/Header/Type%3DFilter.svg",
    "keywords": "type filter data grid header"
  },
  {
    "name": "Type=More",
    "group": "Data Grid / Header",
    "url": "/icon/Data%20Grid/Header/Type%3DMore.svg",
    "keywords": "type more data grid header"
  },
  {
    "name": "Add",
    "group": "Default",
    "url": "/icon/Add.svg",
    "keywords": "add"
  },
  {
    "name": "Add-sm",
    "group": "Default",
    "url": "/icon/Add-sm.svg",
    "keywords": "add sm"
  },
  {
    "name": "AddFill",
    "group": "Default",
    "url": "/icon/AddFill.svg",
    "keywords": "addfill"
  },
  {
    "name": "Admin",
    "group": "Default",
    "url": "/icon/Admin.svg",
    "keywords": "admin"
  },
  {
    "name": "AI_Control",
    "group": "Default",
    "url": "/icon/AI_Control.svg",
    "keywords": "ai control"
  },
  {
    "name": "AI_Core",
    "group": "Default",
    "url": "/icon/AI_Core.svg",
    "keywords": "ai core"
  },
  {
    "name": "AI_Tool",
    "group": "Default",
    "url": "/icon/AI_Tool.svg",
    "keywords": "ai tool"
  },
  {
    "name": "AiAgent",
    "group": "Default",
    "url": "/icon/AiAgent.svg",
    "keywords": "aiagent"
  },
  {
    "name": "AiEdit",
    "group": "Default",
    "url": "/icon/AiEdit.svg",
    "keywords": "aiedit"
  },
  {
    "name": "Alert",
    "group": "Default",
    "url": "/icon/Alert.svg",
    "keywords": "alert"
  },
  {
    "name": "Analytics",
    "group": "Default",
    "url": "/icon/Analytics.svg",
    "keywords": "analytics"
  },
  {
    "name": "Annotation",
    "group": "Default",
    "url": "/icon/Annotation.svg",
    "keywords": "annotation"
  },
  {
    "name": "API",
    "group": "Default",
    "url": "/icon/API.svg",
    "keywords": "api"
  },
  {
    "name": "Approval",
    "group": "Default",
    "url": "/icon/Approval.svg",
    "keywords": "approval"
  },
  {
    "name": "Approval-2",
    "group": "Default",
    "url": "/icon/Approval-2.svg",
    "keywords": "approval 2"
  },
  {
    "name": "Archive",
    "group": "Default",
    "url": "/icon/Archive.svg",
    "keywords": "archive"
  },
  {
    "name": "Arrow-Forward",
    "group": "Default",
    "url": "/icon/Arrow-Forward.svg",
    "keywords": "arrow forward"
  },
  {
    "name": "ArrowDown",
    "group": "Default",
    "url": "/icon/ArrowDown.svg",
    "keywords": "arrowdown"
  },
  {
    "name": "ArrowDown-1",
    "group": "Default",
    "url": "/icon/ArrowDown-1.svg",
    "keywords": "arrowdown 1"
  },
  {
    "name": "ArrowLeft",
    "group": "Default",
    "url": "/icon/ArrowLeft.svg",
    "keywords": "arrowleft"
  },
  {
    "name": "ArrowRight",
    "group": "Default",
    "url": "/icon/ArrowRight.svg",
    "keywords": "arrowright"
  },
  {
    "name": "ArrowTopLeft",
    "group": "Default",
    "url": "/icon/ArrowTopLeft.svg",
    "keywords": "arrowtopleft"
  },
  {
    "name": "ArrowTopRight",
    "group": "Default",
    "url": "/icon/ArrowTopRight.svg",
    "keywords": "arrowtopright"
  },
  {
    "name": "ArrowUp",
    "group": "Default",
    "url": "/icon/ArrowUp.svg",
    "keywords": "arrowup"
  },
  {
    "name": "Attachment",
    "group": "Default",
    "url": "/icon/Attachment.svg",
    "keywords": "attachment"
  },
  {
    "name": "Author",
    "group": "Default",
    "url": "/icon/Author.svg",
    "keywords": "author"
  },
  {
    "name": "Back",
    "group": "Default",
    "url": "/icon/Back.svg",
    "keywords": "back"
  },
  {
    "name": "Bookmark-Line",
    "group": "Default",
    "url": "/icon/Bookmark-Line.svg",
    "keywords": "bookmark line"
  },
  {
    "name": "Box",
    "group": "Default",
    "url": "/icon/Box.svg",
    "keywords": "box"
  },
  {
    "name": "Bubble",
    "group": "Default",
    "url": "/icon/Bubble.svg",
    "keywords": "bubble"
  },
  {
    "name": "Calendar",
    "group": "Default",
    "url": "/icon/Calendar.svg",
    "keywords": "calendar"
  },
  {
    "name": "Chain",
    "group": "Default",
    "url": "/icon/Chain.svg",
    "keywords": "chain"
  },
  {
    "name": "Chat",
    "group": "Default",
    "url": "/icon/Chat.svg",
    "keywords": "chat"
  },
  {
    "name": "Chat Add",
    "group": "Default",
    "url": "/icon/Chat%20Add.svg",
    "keywords": "chat add"
  },
  {
    "name": "Chatbot",
    "group": "Default",
    "url": "/icon/Chatbot.svg",
    "keywords": "chatbot"
  },
  {
    "name": "Check",
    "group": "Default",
    "url": "/icon/Check.svg",
    "keywords": "check"
  },
  {
    "name": "CheckCircle",
    "group": "Default",
    "url": "/icon/CheckCircle.svg",
    "keywords": "checkcircle"
  },
  {
    "name": "CheckCircleFill",
    "group": "Default",
    "url": "/icon/CheckCircleFill.svg",
    "keywords": "checkcirclefill"
  },
  {
    "name": "ChevronDown",
    "group": "Default",
    "url": "/icon/ChevronDown.svg",
    "keywords": "chevrondown"
  },
  {
    "name": "ChevronDown Fill",
    "group": "Default",
    "url": "/icon/ChevronDown%20Fill.svg",
    "keywords": "chevrondown fill"
  },
  {
    "name": "ChevronLeft",
    "group": "Default",
    "url": "/icon/ChevronLeft.svg",
    "keywords": "chevronleft"
  },
  {
    "name": "ChevronLeft Fill",
    "group": "Default",
    "url": "/icon/ChevronLeft%20Fill.svg",
    "keywords": "chevronleft fill"
  },
  {
    "name": "ChevronRight",
    "group": "Default",
    "url": "/icon/ChevronRight.svg",
    "keywords": "chevronright"
  },
  {
    "name": "ChevronRight Fill",
    "group": "Default",
    "url": "/icon/ChevronRight%20Fill.svg",
    "keywords": "chevronright fill"
  },
  {
    "name": "ChevronUp",
    "group": "Default",
    "url": "/icon/ChevronUp.svg",
    "keywords": "chevronup"
  },
  {
    "name": "ChevronUp Fill",
    "group": "Default",
    "url": "/icon/ChevronUp%20Fill.svg",
    "keywords": "chevronup fill"
  },
  {
    "name": "Clock",
    "group": "Default",
    "url": "/icon/Clock.svg",
    "keywords": "clock"
  },
  {
    "name": "Clock-1",
    "group": "Default",
    "url": "/icon/Clock-1.svg",
    "keywords": "clock 1"
  },
  {
    "name": "Close",
    "group": "Default",
    "url": "/icon/Close.svg",
    "keywords": "close"
  },
  {
    "name": "Close-2",
    "group": "Default",
    "url": "/icon/Close-2.svg",
    "keywords": "close 2"
  },
  {
    "name": "CloseCircle",
    "group": "Default",
    "url": "/icon/CloseCircle.svg",
    "keywords": "closecircle"
  },
  {
    "name": "CloseCircleFill",
    "group": "Default",
    "url": "/icon/CloseCircleFill.svg",
    "keywords": "closecirclefill"
  },
  {
    "name": "CloudUpload",
    "group": "Default",
    "url": "/icon/CloudUpload.svg",
    "keywords": "cloudupload"
  },
  {
    "name": "Collapse",
    "group": "Default",
    "url": "/icon/Collapse.svg",
    "keywords": "collapse"
  },
  {
    "name": "Collapse-1",
    "group": "Default",
    "url": "/icon/Collapse-1.svg",
    "keywords": "collapse 1"
  },
  {
    "name": "Collapse-2",
    "group": "Default",
    "url": "/icon/Collapse-2.svg",
    "keywords": "collapse 2"
  },
  {
    "name": "CollapseAll",
    "group": "Default",
    "url": "/icon/CollapseAll.svg",
    "keywords": "collapseall"
  },
  {
    "name": "Collection",
    "group": "Default",
    "url": "/icon/Collection.svg",
    "keywords": "collection"
  },
  {
    "name": "Config",
    "group": "Default",
    "url": "/icon/Config.svg",
    "keywords": "config"
  },
  {
    "name": "Configuration",
    "group": "Default",
    "url": "/icon/Configuration.svg",
    "keywords": "configuration"
  },
  {
    "name": "Connection",
    "group": "Default",
    "url": "/icon/Connection.svg",
    "keywords": "connection"
  },
  {
    "name": "ConnectionSetting",
    "group": "Default",
    "url": "/icon/ConnectionSetting.svg",
    "keywords": "connectionsetting"
  },
  {
    "name": "Connector",
    "group": "Default",
    "url": "/icon/Connector.svg",
    "keywords": "connector"
  },
  {
    "name": "Copy",
    "group": "Default",
    "url": "/icon/Copy.svg",
    "keywords": "copy"
  },
  {
    "name": "cpu",
    "group": "Default",
    "url": "/icon/cpu.svg",
    "keywords": "cpu"
  },
  {
    "name": "CreateDoc",
    "group": "Default",
    "url": "/icon/CreateDoc.svg",
    "keywords": "createdoc"
  },
  {
    "name": "CreateTable",
    "group": "Default",
    "url": "/icon/CreateTable.svg",
    "keywords": "createtable"
  },
  {
    "name": "DashedCircle",
    "group": "Default",
    "url": "/icon/DashedCircle.svg",
    "keywords": "dashedcircle"
  },
  {
    "name": "DataAnalysis",
    "group": "Default",
    "url": "/icon/DataAnalysis.svg",
    "keywords": "dataanalysis"
  },
  {
    "name": "DataAnalysis-1",
    "group": "Default",
    "url": "/icon/DataAnalysis-1.svg",
    "keywords": "dataanalysis 1"
  },
  {
    "name": "Distribution",
    "group": "Default",
    "url": "/icon/Distribution.svg",
    "keywords": "distribution"
  },
  {
    "name": "Document",
    "group": "Default",
    "url": "/icon/Document.svg",
    "keywords": "document"
  },
  {
    "name": "Document_Add",
    "group": "Default",
    "url": "/icon/Document_Add.svg",
    "keywords": "document add"
  },
  {
    "name": "Document_Merge",
    "group": "Default",
    "url": "/icon/Document_Merge.svg",
    "keywords": "document merge"
  },
  {
    "name": "Document_Multi",
    "group": "Default",
    "url": "/icon/Document_Multi.svg",
    "keywords": "document multi"
  },
  {
    "name": "DocumentBlank",
    "group": "Default",
    "url": "/icon/DocumentBlank.svg",
    "keywords": "documentblank"
  },
  {
    "name": "Dot",
    "group": "Default",
    "url": "/icon/Dot.svg",
    "keywords": "dot"
  },
  {
    "name": "DoubleChevronDown",
    "group": "Default",
    "url": "/icon/DoubleChevronDown.svg",
    "keywords": "doublechevrondown"
  },
  {
    "name": "DoubleChevronLeft",
    "group": "Default",
    "url": "/icon/DoubleChevronLeft.svg",
    "keywords": "doublechevronleft"
  },
  {
    "name": "DoubleChevronRight",
    "group": "Default",
    "url": "/icon/DoubleChevronRight.svg",
    "keywords": "doublechevronright"
  },
  {
    "name": "DoubleChevronUp",
    "group": "Default",
    "url": "/icon/DoubleChevronUp.svg",
    "keywords": "doublechevronup"
  },
  {
    "name": "Download",
    "group": "Default",
    "url": "/icon/Download.svg",
    "keywords": "download"
  },
  {
    "name": "DragHandle",
    "group": "Default",
    "url": "/icon/DragHandle.svg",
    "keywords": "draghandle"
  },
  {
    "name": "Drivers",
    "group": "Default",
    "url": "/icon/Drivers.svg",
    "keywords": "drivers"
  },
  {
    "name": "EditSuccess",
    "group": "Default",
    "url": "/icon/EditSuccess.svg",
    "keywords": "editsuccess"
  },
  {
    "name": "EmptyData",
    "group": "Default",
    "url": "/icon/EmptyData.svg",
    "keywords": "emptydata"
  },
  {
    "name": "EmptyImage",
    "group": "Default",
    "url": "/icon/EmptyImage.svg",
    "keywords": "emptyimage"
  },
  {
    "name": "EmptyTable",
    "group": "Default",
    "url": "/icon/EmptyTable.svg",
    "keywords": "emptytable"
  },
  {
    "name": "EmptyUpload",
    "group": "Default",
    "url": "/icon/EmptyUpload.svg",
    "keywords": "emptyupload"
  },
  {
    "name": "End",
    "group": "Default",
    "url": "/icon/End.svg",
    "keywords": "end"
  },
  {
    "name": "Event",
    "group": "Default",
    "url": "/icon/Event.svg",
    "keywords": "event"
  },
  {
    "name": "Execution result",
    "group": "Default",
    "url": "/icon/Execution%20result.svg",
    "keywords": "execution result"
  },
  {
    "name": "Expand",
    "group": "Default",
    "url": "/icon/Expand.svg",
    "keywords": "expand"
  },
  {
    "name": "Expand-1",
    "group": "Default",
    "url": "/icon/Expand-1.svg",
    "keywords": "expand 1"
  },
  {
    "name": "Expand-2",
    "group": "Default",
    "url": "/icon/Expand-2.svg",
    "keywords": "expand 2"
  },
  {
    "name": "ExpandAll",
    "group": "Default",
    "url": "/icon/ExpandAll.svg",
    "keywords": "expandall"
  },
  {
    "name": "Filter",
    "group": "Default",
    "url": "/icon/Filter.svg",
    "keywords": "filter"
  },
  {
    "name": "Flag",
    "group": "Default",
    "url": "/icon/Flag.svg",
    "keywords": "flag"
  },
  {
    "name": "Flag Filled",
    "group": "Default",
    "url": "/icon/Flag%20Filled.svg",
    "keywords": "flag filled"
  },
  {
    "name": "Flag-1",
    "group": "Default",
    "url": "/icon/Flag-1.svg",
    "keywords": "flag 1"
  },
  {
    "name": "Flash",
    "group": "Default",
    "url": "/icon/Flash.svg",
    "keywords": "flash"
  },
  {
    "name": "Folder",
    "group": "Default",
    "url": "/icon/Folder.svg",
    "keywords": "folder"
  },
  {
    "name": "Folder Fill",
    "group": "Default",
    "url": "/icon/Folder%20Fill.svg",
    "keywords": "folder fill"
  },
  {
    "name": "FolderSetting",
    "group": "Default",
    "url": "/icon/FolderSetting.svg",
    "keywords": "foldersetting"
  },
  {
    "name": "Fork",
    "group": "Default",
    "url": "/icon/Fork.svg",
    "keywords": "fork"
  },
  {
    "name": "Fullscreen",
    "group": "Default",
    "url": "/icon/Fullscreen.svg",
    "keywords": "fullscreen"
  },
  {
    "name": "Gear",
    "group": "Default",
    "url": "/icon/Gear.svg",
    "keywords": "gear"
  },
  {
    "name": "Gears",
    "group": "Default",
    "url": "/icon/Gears.svg",
    "keywords": "gears"
  },
  {
    "name": "Grid-1",
    "group": "Default",
    "url": "/icon/Grid-1.svg",
    "keywords": "grid 1"
  },
  {
    "name": "Grid-2",
    "group": "Default",
    "url": "/icon/Grid-2.svg",
    "keywords": "grid 2"
  },
  {
    "name": "Hide",
    "group": "Default",
    "url": "/icon/Hide.svg",
    "keywords": "hide"
  },
  {
    "name": "History",
    "group": "Default",
    "url": "/icon/History.svg",
    "keywords": "history"
  },
  {
    "name": "Home",
    "group": "Default",
    "url": "/icon/Home.svg",
    "keywords": "home"
  },
  {
    "name": "Image",
    "group": "Default",
    "url": "/icon/Image.svg",
    "keywords": "image"
  },
  {
    "name": "Info",
    "group": "Default",
    "url": "/icon/Info.svg",
    "keywords": "info"
  },
  {
    "name": "InfoFill",
    "group": "Default",
    "url": "/icon/InfoFill.svg",
    "keywords": "infofill"
  },
  {
    "name": "INFRA_IO",
    "group": "Default",
    "url": "/icon/INFRA_IO.svg",
    "keywords": "infra io"
  },
  {
    "name": "Items",
    "group": "Default",
    "url": "/icon/Items.svg",
    "keywords": "items"
  },
  {
    "name": "Json",
    "group": "Default",
    "url": "/icon/Json.svg",
    "keywords": "json"
  },
  {
    "name": "KL-Base",
    "group": "Default",
    "url": "/icon/KL-Base.svg",
    "keywords": "kl base"
  },
  {
    "name": "KL-Base (Custom)",
    "group": "Default",
    "url": "/icon/KL-Base%20(Custom).svg",
    "keywords": "kl base custom"
  },
  {
    "name": "KL-Base (OCR)",
    "group": "Default",
    "url": "/icon/KL-Base%20(OCR).svg",
    "keywords": "kl base ocr"
  },
  {
    "name": "KL-Custom",
    "group": "Default",
    "url": "/icon/KL-Custom.svg",
    "keywords": "kl custom"
  },
  {
    "name": "KL-Layout",
    "group": "Default",
    "url": "/icon/KL-Layout.svg",
    "keywords": "kl layout"
  },
  {
    "name": "KL-Layout (Custom)",
    "group": "Default",
    "url": "/icon/KL-Layout%20(Custom).svg",
    "keywords": "kl layout custom"
  },
  {
    "name": "KL-Layout (OCR)",
    "group": "Default",
    "url": "/icon/KL-Layout%20(OCR).svg",
    "keywords": "kl layout ocr"
  },
  {
    "name": "KL-LLM",
    "group": "Default",
    "url": "/icon/KL-LLM.svg",
    "keywords": "kl llm"
  },
  {
    "name": "Layout",
    "group": "Default",
    "url": "/icon/Layout.svg",
    "keywords": "layout"
  },
  {
    "name": "Link",
    "group": "Default",
    "url": "/icon/Link.svg",
    "keywords": "link"
  },
  {
    "name": "List",
    "group": "Default",
    "url": "/icon/List.svg",
    "keywords": "list"
  },
  {
    "name": "Loader",
    "group": "Default",
    "url": "/icon/Loader.svg",
    "keywords": "loader"
  },
  {
    "name": "Loading",
    "group": "Default",
    "url": "/icon/Loading.svg",
    "keywords": "loading"
  },
  {
    "name": "LoadingTime",
    "group": "Default",
    "url": "/icon/LoadingTime.svg",
    "keywords": "loadingtime"
  },
  {
    "name": "LoadsTimer",
    "group": "Default",
    "url": "/icon/LoadsTimer.svg",
    "keywords": "loadstimer"
  },
  {
    "name": "Lock",
    "group": "Default",
    "url": "/icon/Lock.svg",
    "keywords": "lock"
  },
  {
    "name": "Lock-Fill",
    "group": "Default",
    "url": "/icon/Lock-Fill.svg",
    "keywords": "lock fill"
  },
  {
    "name": "Logo_light",
    "group": "Default",
    "url": "/icon/Logo_light.svg",
    "keywords": "logo light"
  },
  {
    "name": "Logout",
    "group": "Default",
    "url": "/icon/Logout.svg",
    "keywords": "logout"
  },
  {
    "name": "Manual",
    "group": "Default",
    "url": "/icon/Manual.svg",
    "keywords": "manual"
  },
  {
    "name": "MenuSearch",
    "group": "Default",
    "url": "/icon/MenuSearch.svg",
    "keywords": "menusearch"
  },
  {
    "name": "Minus",
    "group": "Default",
    "url": "/icon/Minus.svg",
    "keywords": "minus"
  },
  {
    "name": "Minus-sm",
    "group": "Default",
    "url": "/icon/Minus-sm.svg",
    "keywords": "minus sm"
  },
  {
    "name": "MinusFill",
    "group": "Default",
    "url": "/icon/MinusFill.svg",
    "keywords": "minusfill"
  },
  {
    "name": "mirror",
    "group": "Default",
    "url": "/icon/mirror.svg",
    "keywords": "mirror"
  },
  {
    "name": "Model",
    "group": "Default",
    "url": "/icon/Model.svg",
    "keywords": "model"
  },
  {
    "name": "Model-Validate",
    "group": "Default",
    "url": "/icon/Model-Validate.svg",
    "keywords": "model validate"
  },
  {
    "name": "Monitoring",
    "group": "Default",
    "url": "/icon/Monitoring.svg",
    "keywords": "monitoring"
  },
  {
    "name": "Moon",
    "group": "Default",
    "url": "/icon/Moon.svg",
    "keywords": "moon"
  },
  {
    "name": "MoreHorizontal",
    "group": "Default",
    "url": "/icon/MoreHorizontal.svg",
    "keywords": "morehorizontal"
  },
  {
    "name": "MoreVertical",
    "group": "Default",
    "url": "/icon/MoreVertical.svg",
    "keywords": "morevertical"
  },
  {
    "name": "My Flow",
    "group": "Default",
    "url": "/icon/My%20Flow.svg",
    "keywords": "my flow"
  },
  {
    "name": "MyAgent",
    "group": "Default",
    "url": "/icon/MyAgent.svg",
    "keywords": "myagent"
  },
  {
    "name": "Node Link",
    "group": "Default",
    "url": "/icon/Node%20Link.svg",
    "keywords": "node link"
  },
  {
    "name": "Note",
    "group": "Default",
    "url": "/icon/Note.svg",
    "keywords": "note"
  },
  {
    "name": "Noti",
    "group": "Default",
    "url": "/icon/Noti.svg",
    "keywords": "noti"
  },
  {
    "name": "Notice",
    "group": "Default",
    "url": "/icon/Notice.svg",
    "keywords": "notice"
  },
  {
    "name": "Overlap",
    "group": "Default",
    "url": "/icon/Overlap.svg",
    "keywords": "overlap"
  },
  {
    "name": "Pause",
    "group": "Default",
    "url": "/icon/Pause.svg",
    "keywords": "pause"
  },
  {
    "name": "PDF",
    "group": "Default",
    "url": "/icon/PDF.svg",
    "keywords": "pdf"
  },
  {
    "name": "Pencil-Line",
    "group": "Default",
    "url": "/icon/Pencil-Line.svg",
    "keywords": "pencil line"
  },
  {
    "name": "Permission",
    "group": "Default",
    "url": "/icon/Permission.svg",
    "keywords": "permission"
  },
  {
    "name": "Pin",
    "group": "Default",
    "url": "/icon/Pin.svg",
    "keywords": "pin"
  },
  {
    "name": "Pipeline",
    "group": "Default",
    "url": "/icon/Pipeline.svg",
    "keywords": "pipeline"
  },
  {
    "name": "Play",
    "group": "Default",
    "url": "/icon/Play.svg",
    "keywords": "play"
  },
  {
    "name": "PlayTriangle_2",
    "group": "Default",
    "url": "/icon/PlayTriangle_2.svg",
    "keywords": "playtriangle 2"
  },
  {
    "name": "Popup",
    "group": "Default",
    "url": "/icon/Popup.svg",
    "keywords": "popup"
  },
  {
    "name": "ProjectHistory",
    "group": "Default",
    "url": "/icon/ProjectHistory.svg",
    "keywords": "projecthistory"
  },
  {
    "name": "Prompt",
    "group": "Default",
    "url": "/icon/Prompt.svg",
    "keywords": "prompt"
  },
  {
    "name": "Provider",
    "group": "Default",
    "url": "/icon/Provider.svg",
    "keywords": "provider"
  },
  {
    "name": "Question Fill",
    "group": "Default",
    "url": "/icon/Question%20Fill.svg",
    "keywords": "question fill"
  },
  {
    "name": "Recommend",
    "group": "Default",
    "url": "/icon/Recommend.svg",
    "keywords": "recommend"
  },
  {
    "name": "Refresh",
    "group": "Default",
    "url": "/icon/Refresh.svg",
    "keywords": "refresh"
  },
  {
    "name": "Refresh-1",
    "group": "Default",
    "url": "/icon/Refresh-1.svg",
    "keywords": "refresh 1"
  },
  {
    "name": "Refresh-scr",
    "group": "Default",
    "url": "/icon/Refresh-scr.svg",
    "keywords": "refresh scr"
  },
  {
    "name": "Reindex",
    "group": "Default",
    "url": "/icon/Reindex.svg",
    "keywords": "reindex"
  },
  {
    "name": "Resize",
    "group": "Default",
    "url": "/icon/Resize.svg",
    "keywords": "resize"
  },
  {
    "name": "Rocket Fill",
    "group": "Default",
    "url": "/icon/Rocket%20Fill.svg",
    "keywords": "rocket fill"
  },
  {
    "name": "Save",
    "group": "Default",
    "url": "/icon/Save.svg",
    "keywords": "save"
  },
  {
    "name": "Search",
    "group": "Default",
    "url": "/icon/Search.svg",
    "keywords": "search"
  },
  {
    "name": "Send",
    "group": "Default",
    "url": "/icon/Send.svg",
    "keywords": "send"
  },
  {
    "name": "Server",
    "group": "Default",
    "url": "/icon/Server.svg",
    "keywords": "server"
  },
  {
    "name": "Service call",
    "group": "Default",
    "url": "/icon/Service%20call.svg",
    "keywords": "service call"
  },
  {
    "name": "ServiceChange",
    "group": "Default",
    "url": "/icon/ServiceChange.svg",
    "keywords": "servicechange"
  },
  {
    "name": "Share",
    "group": "Default",
    "url": "/icon/Share.svg",
    "keywords": "share"
  },
  {
    "name": "Size",
    "group": "Default",
    "url": "/icon/Size.svg",
    "keywords": "size"
  },
  {
    "name": "Smiley",
    "group": "Default",
    "url": "/icon/Smiley.svg",
    "keywords": "smiley"
  },
  {
    "name": "Snapshot create",
    "group": "Default",
    "url": "/icon/Snapshot%20create.svg",
    "keywords": "snapshot create"
  },
  {
    "name": "Snapshot list",
    "group": "Default",
    "url": "/icon/Snapshot%20list.svg",
    "keywords": "snapshot list"
  },
  {
    "name": "Staging",
    "group": "Default",
    "url": "/icon/Staging.svg",
    "keywords": "staging"
  },
  {
    "name": "Star",
    "group": "Default",
    "url": "/icon/Star.svg",
    "keywords": "star"
  },
  {
    "name": "StarFill",
    "group": "Default",
    "url": "/icon/StarFill.svg",
    "keywords": "starfill"
  },
  {
    "name": "Status",
    "group": "Default",
    "url": "/icon/Status.svg",
    "keywords": "status"
  },
  {
    "name": "Status-2",
    "group": "Default",
    "url": "/icon/Status-2.svg",
    "keywords": "status 2"
  },
  {
    "name": "Stock",
    "group": "Default",
    "url": "/icon/Stock.svg",
    "keywords": "stock"
  },
  {
    "name": "StopSquare_2",
    "group": "Default",
    "url": "/icon/StopSquare_2.svg",
    "keywords": "stopsquare 2"
  },
  {
    "name": "Structure",
    "group": "Default",
    "url": "/icon/Structure.svg",
    "keywords": "structure"
  },
  {
    "name": "Studio",
    "group": "Default",
    "url": "/icon/Studio.svg",
    "keywords": "studio"
  },
  {
    "name": "Studio-Action",
    "group": "Default",
    "url": "/icon/Studio-Action.svg",
    "keywords": "studio action"
  },
  {
    "name": "Studio-Execution result",
    "group": "Default",
    "url": "/icon/Studio-Execution%20result.svg",
    "keywords": "studio execution result"
  },
  {
    "name": "Studio-Input form",
    "group": "Default",
    "url": "/icon/Studio-Input%20form.svg",
    "keywords": "studio input form"
  },
  {
    "name": "Studio-Manual execution",
    "group": "Default",
    "url": "/icon/Studio-Manual%20execution.svg",
    "keywords": "studio manual execution"
  },
  {
    "name": "Studio-Trigger",
    "group": "Default",
    "url": "/icon/Studio-Trigger.svg",
    "keywords": "studio trigger"
  },
  {
    "name": "Sun",
    "group": "Default",
    "url": "/icon/Sun.svg",
    "keywords": "sun"
  },
  {
    "name": "Table",
    "group": "Default",
    "url": "/icon/Table.svg",
    "keywords": "table"
  },
  {
    "name": "Thinking",
    "group": "Default",
    "url": "/icon/Thinking.svg",
    "keywords": "thinking"
  },
  {
    "name": "Thumbs down",
    "group": "Default",
    "url": "/icon/Thumbs%20down.svg",
    "keywords": "thumbs down"
  },
  {
    "name": "Thumbs up",
    "group": "Default",
    "url": "/icon/Thumbs%20up.svg",
    "keywords": "thumbs up"
  },
  {
    "name": "Token Used",
    "group": "Default",
    "url": "/icon/Token%20Used.svg",
    "keywords": "token used"
  },
  {
    "name": "Tool",
    "group": "Default",
    "url": "/icon/Tool.svg",
    "keywords": "tool"
  },
  {
    "name": "Transfer",
    "group": "Default",
    "url": "/icon/Transfer.svg",
    "keywords": "transfer"
  },
  {
    "name": "Trash",
    "group": "Default",
    "url": "/icon/Trash.svg",
    "keywords": "trash"
  },
  {
    "name": "Unknown",
    "group": "Default",
    "url": "/icon/Unknown.svg",
    "keywords": "unknown"
  },
  {
    "name": "Unlink",
    "group": "Default",
    "url": "/icon/Unlink.svg",
    "keywords": "unlink"
  },
  {
    "name": "Upload",
    "group": "Default",
    "url": "/icon/Upload.svg",
    "keywords": "upload"
  },
  {
    "name": "User",
    "group": "Default",
    "url": "/icon/User.svg",
    "keywords": "user"
  },
  {
    "name": "User History",
    "group": "Default",
    "url": "/icon/User%20History.svg",
    "keywords": "user history"
  },
  {
    "name": "Users",
    "group": "Default",
    "url": "/icon/Users.svg",
    "keywords": "users"
  },
  {
    "name": "Variation Management",
    "group": "Default",
    "url": "/icon/Variation%20Management.svg",
    "keywords": "variation management"
  },
  {
    "name": "View",
    "group": "Default",
    "url": "/icon/View.svg",
    "keywords": "view"
  },
  {
    "name": "View Details",
    "group": "Default",
    "url": "/icon/View%20Details.svg",
    "keywords": "view details"
  },
  {
    "name": "Violation",
    "group": "Default",
    "url": "/icon/Violation.svg",
    "keywords": "violation"
  },
  {
    "name": "Warning",
    "group": "Default",
    "url": "/icon/Warning.svg",
    "keywords": "warning"
  },
  {
    "name": "WarningFill",
    "group": "Default",
    "url": "/icon/WarningFill.svg",
    "keywords": "warningfill"
  },
  {
    "name": "WebSearch",
    "group": "Default",
    "url": "/icon/WebSearch.svg",
    "keywords": "websearch"
  },
  {
    "name": "WhiteLabel",
    "group": "Default",
    "url": "/icon/WhiteLabel.svg",
    "keywords": "whitelabel"
  },
  {
    "name": "WorkMode",
    "group": "Default",
    "url": "/icon/WorkMode.svg",
    "keywords": "workmode"
  },
  {
    "name": "Zoom In",
    "group": "Default",
    "url": "/icon/Zoom%20In.svg",
    "keywords": "zoom in"
  },
  {
    "name": "Bubble",
    "group": "Item",
    "url": "/icon/Item/Bubble.svg",
    "keywords": "bubble item"
  }
] as const;

export const ICON_GROUPS: readonly string[] = [
  "Data Grid / Header",
  "Default",
  "Item"
] as const;
